# Generated by Django 3.1 on 2020-11-13 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201114_0128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='surname',
            new_name='last_name',
        ),
    ]
